version: 2.1

orbs:
  snyk: snyk/snyk@1.1.2

jobs:
  build-and-push:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: "Build image"
          command: |
            docker build -t colwyn-me:latest .
      - snyk/scan:
          docker-image-name: colwyn-me:latest
          fail-on-issues: false # the nginx base image has a critical vuln right now
      - run:
          name: "Push images"
          command: |
            echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            REMOTE_REPO='colwynmyself/colwyn-me'

            if [[ "${CIRCLE_BRANCH}" == 'main' ]]; then
              docker tag colwyn-me:latest "${REMOTE_REPO}:latest"
              docker push "${REMOTE_REPO}:latest"
            fi

            docker tag colwyn-me:latest "${REMOTE_REPO}:${CIRCLE_SHA1}"
            docker push "${REMOTE_REPO}:${CIRCLE_SHA1}"
            docker tag colwyn-me:latest "${REMOTE_REPO}:${CIRCLE_BRANCH}"
            docker push "${REMOTE_REPO}:${CIRCLE_BRANCH}"
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Install deps"
          command: |
            apt-get update
            apt-get install -y curl jq
      - run:
          name: "Deploy to DigitalOcean"
          command: ./deploy/digital-ocean.sh

workflows:
  bulid-and-push:
    jobs:
      - build-and-push:
          context:
            - dockerhub
            - snyk
      - deploy:
          requires: [build-and-push]
          context:
            - digitalocean
